# Generated by Django 3.2.14 on 2022-07-26 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('band_id', models.IntegerField()),
                ('band_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('coverage', models.CharField(default='outdoor', max_length=10)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sector', models.IntegerField()),
                ('azimuth', models.FloatField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='liveapp.node')),
            ],
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='liveapp.cell')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='liveapp.sector'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(fields=('node', 'sector'), name='unique_node_sector'),
        ),
        migrations.AddConstraint(
            model_name='kpi',
            constraint=models.UniqueConstraint(fields=('cell', 'name', 'date'), name='unique_cell_name_date'),
        ),
    ]
